### ISSUE TITLE
need to be able to run (some) test cases on non-template files

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#104]
E.g. the test case that checks the templates for hard-coded endpoints in templates, needs to be extended to other files in the sample/project - for example scripts (sh, ps1) need to also be checked for the endpoints...

currently we only check json files with the proper schema

**Comment by StartAutomating** [comment]
@bmoore-msft we can handle this without that significant change by adding a new test group, "AllFiles" and making that test group run on all items found by our target file (in most cases, all items in that directory).

This would be useful for others as well, since it gives them a path to write tests ensuring that files/directories are structured the way they would prefer.
