### ISSUE TITLE
IDs Should Be Derived From ResourceIDs fails in vnet template

### ISSUE THREAD

**Issue by drawshah** [Azure/arm-ttk#164]
Using the Azure DevOps task i get the following error when it is testing the template at the bottom of post

Error message
Microsoft.PowerShell.Commands.WriteErrorException: Blank ID Property found: 
id                                                                              ParentObject                           
--                                                                              ------------                           
[resourceId('Microsoft.Network/networkSecurityGroups', parameters('nsg-name'))] {@{addressPrefix=[parameters('vnetAd...

 in template file vnet_template.json
Stack trace
at &lt;ScriptBlock&gt;, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\testcases\deploymentTemplate\IDs-Should-Be-Derived-From-ResourceIDs.test.ps1: line 61
at Test-Case, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 190
at Test-Group, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 214
at Test-FileList, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 334
at Test-AzTemplate&lt;End&gt;, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 480
at Test-FolderContents, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\invoke-ttk.psm1: line 12
at Invoke-TTK, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\invoke-ttk.psm1: line 75
at &lt;ScriptBlock&gt;, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\powershell.ps1: line 28
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 1
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 22
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 18
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 1

**vnet_template.json**

{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "location": {
            "type": "string"
        },
        "nsg-name": {
            "type": "string",
            "defaultValue": "test-nsg"
        },
        "virtualNetworkName": {
            "type": "string"
        },
        "vnetAddressPrefix": {
            "type": "string"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Network/networkSecurityGroups",
            "name": "[parameters('nsg-name')]",
            "apiVersion": "2020-04-01",
            "location": "[parameters('location')]",
            "properties": {}
        },
        {
            "type": "Microsoft.Network/virtualNetworks",
            "name": "[parameters('virtualNetworkName')]",
            "apiVersion": "2020-04-01",
            "location": "[parameters('location')]",
            "dependsOn": [
                "[resourceId('Microsoft.Network/networkSecurityGroups', parameters('nsg-name'))]"
            ],
            "properties": {
                "addressSpace": {
                    "addressPrefixes": [
                        "[parameters('vnetAddressPrefix')]"
                    ]
                },
                "subnets": [
                    {
                        "name": "default",
                        "properties": {
                            "addressPrefix": "[parameters('vnetAddressPrefix')]",
                            "networkSecurityGroup": {
                              "id": "[resourceId('Microsoft.Network/networkSecurityGroups', parameters('nsg-name'))]"
                         }                            
                      }
                    }
                ],
                "enableDdosProtection": false,
                "enableVmProtection": false
            }  
        }
    ],
    "outputs": {
        "ip-prefix": {
            "type": "string",
            "value": "[resourceId('Microsoft.Network/virtualNetworks', parameters('virtualNetworkName'))]"
        }
    }
}

**Comment by jpodoba** [comment]
I confirm because I have exactly the same. 
The root cause of that in my case is because I'm try to retrieve MESSAGE id from the resources which is not deployed yet.
I'm use those extension to test templates in CI/CD before they will be ready for production but if the resource is not deployed it will be empty.

My example below:
`
"networkSecurityGroup": {
    "id": "[resourceId('Microsoft.Network/networkSecurityGroups', variables('nsgName'))]"
},
`

**Comment by bmoore-msft** [comment]
@drawshah / @jpodoba  - Are you using Sam's AzDO task?  If so, can you file the issue here:

https://github.com/sam-cogan/arm-ttk-extension/issues

I'm not able to repro on the original template, so want to confirm that's what you're doing...

**Comment by jpodoba** [comment]
Well @bmoore-msft  , you are right, I use Sam's extension but Sam's uses the original test from this repo and I think the root cause is here.

If you want to reproduce the issue try to use resourceId for the resource which not exists yet in Azure and you will get that error.

**Comment by drawshah** [comment]
@bmoore-msft / @jpodoba i have raised https://github.com/sam-cogan/arm-ttk-extension/issues/18

**Comment by sam-cogan** [comment]
@bmoore-msft I've been able to replicate this using the example posted using the TTK directly, so it's not an issue with the extension.

It is this section that is failing:

```
foreach ($id in $ids) { # Then loop over each object with an ID
    $myIdFieldName = $id.PropertyName
    $myId = $id.$myIdFieldName        

```
myIdFieldName is returning "networkSecurityGroup", and so $myId tries to find $id.networkSecurityGroup which doesn't exist, and so fails the check for it being empty.

I'm not very clear on what this part of the test is trying to do.

**Comment by bmoore-msft** [comment]
@jpodoba - I'm happy to look into it more, but I can't reproduce it from the tip - I've tried PS, PS Core and PS Core on linux.  I just copy/pasted the template from the OP into azuredeploy.json and ran the suite.  If there are more details to help repro, feel free to add...

@sam-cogan - I suspect the problem is before then - in Find-JSONContent - does your extension use the copy in your repo?  Or from here?  The copy in your repo is pretty old, so that may be the issue?

**Comment by jpodoba** [comment]
@bmoore-msft thanks for the interest. To avoid typos I've uploaded template file with parameter file into the temporary repo in my [GitHub](https://github.com/jpodoba/temporary). 

You can run the test "IDs-Should-Be-Derived-From-ResourceIDs" for that template file and you should be able to reproduce the issue.

There is one condition. You cannot deploy that template first to Azure. To pass the test it needs to be used "resourceId" but if you will try to use "resourceId" to retrieve that id you will fail. It will fail because the resource does not exist in Azure. It's my option but maybe I'm wrong.

**Comment by bmoore-msft** [comment]
Cool - ok I grabbed from the raw github location but still working as expected for me...  My guess at this point is that the "Find-JSONContent" in your environment is an older version - that's not returning the right properties (which Sam discovered) but it's been fixed in a later version of the framework.

To validate that theory, if you pull from Azure/master or https://arm-ttk/latest and then import-module (have to remove the old one first or use -Force) you shouldn't see the issue if the theory is correct.

**Comment by bmoore-msft** [comment]
oh also - the TTK doesn't do anything with Azure or Azure state - it's all local, so won't be impacted by anything but the source code.

**Comment by jpodoba** [comment]
Got you @bmoore-msft . I us extension from DevOps marketplace so I need to wait for an update instead replace already used task for pull from GitHub. Anyway thanks for you help.

**Comment by sam-cogan** [comment]
Yep, looks like it is an issue with the age of some of the TTK files in the extension. I had though I was updating these in the build but looks like not. I am working on updating these now, but the changes have caused some issues so may be a little while,

**Comment by jpodoba** [comment]
Thank you @sam-cogan it would be great to have that

**Comment by bmoore-msft** [comment]
@jpodoba / @sam-cogan - thanks for confirming...
