### ISSUE TITLE
Different results based on filename

### ISSUE THREAD

**Issue by Ba4bes** [Azure/arm-ttk#176]
I have a template for a basic storage account [link](https://github.com/Ba4bes/SA-AzureDeploy/blob/master/StorageAccount/azuredeploy.json).

When I put this template in a folder and run tests, they all come back positive

![image](https://user-images.githubusercontent.com/43912004/89627832-b8ca0800-d89b-11ea-9ab2-f318dd2ccffd.png)

When I change the name of the template file to azuredeploy2.json, I get a failed test

![image](https://user-images.githubusercontent.com/43912004/89627883-c8e1e780-d89b-11ea-8644-b1a63a43afa9.png)

Everything is the same except the filename, so I would expect these results to be the same

This is running the cmdlet in PowerShell 7, but result in Windows PowerShell was the same. Checked it on a new server 2019 VM as well. Both Pester 5 and pester 4.10.

Just to be sure I also checked the [101 template](https://github.com/Azure/azure-quickstart-templates/blob/master/101-storage-account-create/azuredeploy.json), same results

**Comment by bmoore-msft** [comment]
This is intentional - there are different tests for what is considered the "main" or "primary" template - ie. the entry point for a multi-file deployment... and every other template which is considered to be a nested/linked template.  Linked template should not have a defaultValue for the location property, to ensure that the location from the primary deployment is passed through correctly (otherwise resources can end up not being colocated when they are required to be).

I do think we need #96 to help with this scenario, but will still always have different tests for main and not-main templates.
