### ISSUE TITLE
When template folder contains both azuredeploy.json and mainTemplate.json Outputs-Must-Be-Present-In-Template-Parameters test should check both templates

### ISSUE THREAD

**Issue by arsenvlad** [Azure/arm-ttk#177]
For Azure Managed Application, the template folder contains both azuredeploy.json and mainTemplate.json. When running the test suite and pointing to the template folder, the Outputs-Must-Be-Present-In-Template-Parameters.test.ps1 seems to specifically look in the azuredeploy.json file for the outputs of the createUIDefinition.json instead of looking in the mainTemplate.json and reports that these parameters are not found.
![image](https://user-images.githubusercontent.com/1821568/89744455-b2da4f80-da72-11ea-98fa-cd9758e35738.png)

**Comment by bmoore-msft** [comment]
Actually I think we need to fail the suite on this scenario...  At least as designed currently, there can only be one "entry" point to a deployment.  We determine that by the filename, so if in the folder hierarchy there are 2 "main templates" we need to throw our hands up.

In your scenario, which I assume is similar to this: https://github.com/Azure/azure-quickstart-templates/tree/master/101-managed-application-with-linked-templates you would have to test those folders independently, or somehow otherwise state your intent that you have 2 separate deployments and the files fit together in a particular way.

We *could* pair CUID with a colocated template, but that's not a requirement (except in cases of AMA).

Open to other ideas...

**Comment by arsenvlad** [comment]
Thanks! I agree with your assessment and closing this none-issue.
