### ISSUE TITLE
ApiVersion check conflicts with ARM template schema validation

### ISSUE THREAD

**Issue by MWL88** [Azure/arm-ttk#184]
I am creating a `Microsoft.Automation/automationAccounts` resource with an ARM template specifying the latest [documented](https://docs.microsoft.com/en-us/azure/templates/microsoft.automation/allversions) API version, which is also the latest API version available in the ARM template schema (`2015-10-31`).

When validating the template with the `arm-ttk` it reports the following failure:
```
apiVersions Should Be Recent (20 ms)
        Api versions must be the latest or under 2 years old (730 days) - API version 2015-10-31 of Microsoft.Automation/automationAccounts is 1767 days old
        Valid Api Versions:
        2020-01-13-preview
```

Updating the template to use the API version to the one offered in the validation failure message resolves the `arm-ttk` failure message but now VS Code complains about the API version not being present in the schema.

I have the same experience with `Microsoft.Web/serverfarms` too.

The `arm-ttk` uses the AZ CLI (`az provider list`) to retrieve the list of _valid_ API versions. The data retrieved from the AZ CLI is different to the list of resource providers, resource types and API versions included in the ARM template schema.

Why does the `arm-ttk` not use the ARM template schema as its source of API versions?

I image on-boarding `Microsoft.Web/serverfarms` for auto-generating schema may help for is resource type but the schema for `Microsoft.Automation/automationAccounts` is already auto-generated ... so auto-generating the schema is not the whole fix.

What is the strategy for avoiding this template validation failure in the future?

**Comment by bmoore-msft** [comment]
the /providers api is the source of truth for the platform, so that's why we base the TTK on it.  The schema "completeness" is a separate, nagging, long standing problem we're trying to improve overall.  So the TTK is telling the truth, and fwiw, VS Code is not able to...

In this case it looks like the REST API specs for Microsoft.Automation haven't been updated for, well, years...  And that would be the root cause of this particular RP.

Do you mind filing an issue in this repo for Microsoft.Automation : https://github.com/Azure/azure-rest-api-specs/issues
