### ISSUE TITLE
false positive on parameter reference

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/arm-ttk#193]
See this template for repro: https://github.com/Azure/azure-quickstart-templates/tree/master/101-logic-app-create

The testuri parameter is flagged as not being used but it is used in the workflow definition

**Comment by Splaxi** [comment]
I found the same today. Do you want a hand to fix it?

**Comment by bmoore-msft** [comment]
Please ;)

**Comment by Splaxi** [comment]
The real issue is in fact that the ARM template parameter is named the same as the WorkFlow parameter (Logic App).

So because the language used for ARM templates and the language used for Logic App resembles on so many levels, including parameters, the regex is getting false positives.

From a deployment perspective, the workflow is a bit of wild horse. It is fully supported that we use a ARM parameter inside the workflow definition, while also defining workflow parameters, that we use later in the workflow definition.

When referencing workflow parameter, they must always by enclosed in double quotes, and a @ character, and sometimes inside a set of brackets {}, depending on how advanced the expression is.

Maybe a solution to be to write a regex that will ignore the following:
"@parameters('ParmName')"
"@funtion1(parameters('ParmName'))"
"@{parameters('ParmName')}"
"@{function1(parameters('ParmName'))}"

funtion1 is just to show that there are several builtin functions in the workflow definition that can consume the parameter value.

"@float(string(parameters('ParmName')))" is a valid statement.
"adfasdf@{float(string(parameters('ParmName')))}adsfaf" is a valid statement.

**Comment by Splaxi** [comment]
Looking a bit more into the regex, as there are 2 regex in play here:

$exprStrOrQuote = [Regex]::new('(?<!\\)[\[\"]', 'RightToLeft')

This is the just saying: Find **[** or **"**, from right to left. If I change it to: $exprStrOrQuote = [Regex]::new('(?<!\\)[\[\"@]', 'RightToLeft'), it seems in my testing that it solves the issue.

I'll do a PR right away and let you take it for a spin.

**Comment by bmoore-msft** [comment]
Ok, interesting revelations from #212...  TLDR;

- The syntax of ```@parameters()``` or ```@something(parameters()``` should not be counted as a reference of an ARM template parameter.
- the current test is throwing on any invalid reference() even if there are valid references - that's the current design but a discussion of whether it's correct is warranted
- if the current design is correct (and we should throw on any invalid reference even when there are valid) then we have to figure how to except certain cases if and only if there is also valid reference from ARM.

**Comment by Splaxi** [comment]
I'm on team "Throw on any invalid" references.

If I'm going to invest time into arm-ttk on my projects and we want people to use unit tests like this, it need to keep the bar high.

If people feel the bar is to high, they can either skip the test or we could have 2 versions of it: Strict (Throw on any invalid) or Atleast-Once (If correct is found, skip the testing).

**Comment by StartAutomating** [comment]
@bmoore-msft 👍 The specific case looks like something we can workaround with a lookbehind.  The more general case we could approach in the same sort of way as we approach avoiding inner scope.

**Comment by StartAutomating** [comment]
@bmoore-msft It appears this QuickStart sample no longer exists.  Do we have an alternative we'd like to include in InnerTemplates testing?

**Comment by bmoore-msft** [comment]
It was moved here:  https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.logic/logic-app-create

**Comment by StartAutomating** [comment]
@bmoore-msft : I'm happy to report this quickstart longer has any issues after the innerTemplates changes.

**Comment by bmoore-msft** [comment]
@Splaxi - lmk if you still run into this on the latest bits...
