### ISSUE TITLE
adminUsername Should Not Be A Literal - Cannot index into a null array

### ISSUE THREAD

**Issue by nsucheninov** [Azure/arm-ttk#297]
The test fails on an adminUsername variable in the variables section. It started failing after the test was updated about 2 weeks ago.
'
    "variables": {
        "prefix": "[concat(parameters('prefix'), '-')]",
        "suffix": "[parameters('suffix')]",
        "uniqueSuffix": "[take(uniqueString(resourceGroup().id), 6)]",

        "addressPrefixes": "[parameters('addressPrefixes')]",
        "adminUsername": "[parameters('adminUsername')]",
        "adminPassword": "[parameters('adminPassword')]",

'
The template is attached.
[resources.zip](https://github.com/Azure/arm-ttk/files/5959880/resources.zip)

**Comment by bmoore-msft** [comment]
@StartAutomating - regression?

**Comment by StartAutomating** [comment]
I don't think it was a regression, but it was an easy fix.

we were looking for a specific parentage property which could have never been there in the first place (since we were directly looking beneath .resources and .variables) .

We could also add an ifguard for the parentage if we later determine it to be required.

**Comment by bmoore-msft** [comment]
ok, try now...
