### ISSUE TITLE
Raise error when Maintemplate parameters are not in createUidefinition output

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/arm-ttk#342]
Should we raise error when parameters are not in createUidefinition output? Cert team seems to raise this error and could we catch it when running the tests?

**Comment by bmoore-msft** [comment]
We already have the test here: https://github.com/Azure/arm-ttk/blob/master/arm-ttk/testcases/CreateUIDefinition/Parameters-Without-Default-Must-Exist-In-CreateUIDefinition.test.ps1

the output is only required when there is no defaultValue on the parameter - cert team shouldn't enforce any more than that.

Is the test not working in some scenario or just a discrepancy on what to enforce?

**Comment by santhoshb-msft** [comment]
Hi @bmoore-msft , The tests are working fine, but the cert team insists, that specfically adminUser value should come from createUIDef, while this might be true for solution template, managed apps are little different and as a publisher, I would want to hard my adminUser name so that I have same user across my deployed instance which could be a valid case right?

**Comment by bmoore-msft** [comment]
Sorry - I don't think I completely understand the TTK issue here...  

TTK will ensure that your adminUsername is not hard-coded.  There maybe cases for it (like AMA) but in general that's not a practice we'd endorse.  I would argue that in the AMA case creds should come from keyVault, not raw text in the template.

So it sounds like in your case, you made adminUsername a var (which is blocked unless it's an expression) and if you make it a param instead of a var, the param must come from CUID (unless it has a defaultValue).

So assuming I understand your scenario, the options would be:

- pull creds from KV
- use a variable that contains an expression (it's a hack to get around the test) but "[format({0}, 'root')]" would also pass
- use a parameter with a defaultValue (params w/ defaults do not need to be provided by CUID) - if cert team is overriding that, then use one of the above options or would need to work out the details with the cert team.

Am I missing anything?

**Comment by santhoshb-msft** [comment]
No, I think that makes perfect sense @bmoore-msft !

**Comment by bmoore-msft** [comment]
Ok, thanks for confirming, I'll go ahead and close this out...
