### ISSUE TITLE
Setting adminUser as a variables generates an error in the tests

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/arm-ttk#344]
Setting adminUser as a variables generates an error in the tests? What is better way of doing this are I would like to set as a hardcoded value. I am not allowed to use parameters as I dont want the adminUser set from createUIDefinition.
What is the better approach for this?    

[-] adminUsername Should Not Be A Literal (122 ms)
        AdminUsername is not an expression

**Comment by bmoore-msft** [comment]
credentials should not be hard coded in templates (even via vars) it increases surface area...  if you're not allowed to use parameters then you're being forced into an insecure pattern.

You could pull creds from a config store or keyvault but that would require a persistence resource.  The other pattern is to generate a username using arm functions, but to be truly random would require a parameter.   You could approximate this with the deployment().name function but the username will be deterministic.  E.g.

"adminUsername": "[uniqueString(deployment().name)]"

You could also skip the test in your TTK runs.

Since there's no TTK issue here, I'll close this one out...

**Comment by santhoshb-msft** [comment]
Thanks and understand @bmoore-msft , what approach would you recommend for a managed app and as a publisher I want some consistency across all my customer deployed instances to manage them?
