### ISSUE TITLE
Why is there a test for location not having default value?

### ISSUE THREAD

**Issue by cconrado** [Azure/arm-ttk#38]
Hi There,

So just confused about this test as its documented to have this function as a default value.
![image](https://user-images.githubusercontent.com/9168464/79676869-3adcd680-81b0-11ea-9fca-4b7a6f65ce7e.png)

![image](https://user-images.githubusercontent.com/9168464/79676876-4b8d4c80-81b0-11ea-9db2-194ad5fe52b6.png)

**Comment by bmoore-msft** [comment]
The test is more explicit, the check is for the defaultValue in nested templates... the lack of default here is to ensure that the location (in this case) is passed through to the nested deployment since they almost always need to match.  The docs are a little less specific but that feedback would be helpful (for the docs)
