### ISSUE TITLE
 apiVersions Should Be Recent conflict for Microsoft.Insights/components

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#395]
When using Microsoft.Insights/components in an ARM template there are two options for API definition.

The last full published version is 2015-05-01 which provides this message 

Api versions must be the latest or under 2 years old (730 days) - API version 2015-05-01 of  is 2230 days old

The latest version is 2020-02-02-preview which correctly states there is an Api version that is not preview and should be used.

For this component there is no way to logically pass the test as its either an API in preview or one that is too old.

I know we could disable this test, but that coudl then lead to other API's becoming out of date.

Suggestion, if the API is the latest none preview version then the test should pass even if it is older than 730 days.

Of course the documentation at https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/components?tabs=json could be incorrect.

**Comment by bmoore-msft** [comment]
Ok...

The latest version for Microsoft.Insights/components is 2020-02-02 (non-preview)...  the docs unfortunately lag with apiVersion, the TTK pulls them from the /providers api - which you can invoke with ```Get-AzResourceProvider -ProviderNameSpace "Microsoft.Insights"``` or ```az provider show -n "Microsoft.Insights" -o json```

When I run the test with 2015-05-01 or 2020-02-02 or 2020-02-02-preview - I see the expected behavior in each case.

![image](https://user-images.githubusercontent.com/10090014/121598244-3ce2a400-ca07-11eb-944f-924b20b13af4.png)


![image](https://user-images.githubusercontent.com/10090014/121598270-45d37580-ca07-11eb-959b-ed998a1dc7b2.png)


Are you possibly running an older version of the TTK (we just did a cache update last week)...

**Comment by drewkg** [comment]
Thanks for the explanation, this has resolved the issue I was having with this test in this occasion.

Bit of a moan / suggestion.  Microsoft need to do a better job keeping all their documentation upto date.  This issue is not resolvable from the Azure Template documentation, or from intellisense within VS Code as the most recent API is not surfaced and has to be queried from the API directly.

**Comment by bmoore-msft** [comment]
re: docs I hear you - you're certainly not the only one that has gone down this patch trying to match TTK with "reality".  FWIW,. it's actually more about the resource owners keeping their api specs up to date - docs etc are generated from those and if they aren't updated, docs can never be...  it certainly won't hurt to leave feedback here:

https://docs.microsoft.com/en-us/rest/api/application-insights/components/create-or-update

and/or here:

https://github.com/Azure/azure-rest-api-specs/issues

Sounds like we can close this out for now, feel free to reopen if I missed anything...
