### ISSUE TITLE
Location parameter default Value, allowed Values and linting

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#441]
Ok this might not be an ARM-TTK issue, but the linter in VS Code reports this parameter as an issue as the defaultValue is not contained in the allowed values.  However this does pass ARM-TTK tests, if however we replace the defaultValue with UK South so the linting in VS Code passes ARM-TTK then fails on hard coded defaultValue.

"Location": {
	"type": "string",
	"defaultValue": "[resourceGroup().location]",
	"metadata": {
		"description": "The location of the resources created, excluding 'Global', defaults to the resource group location."
	},
      "allowedValues": [
        "UK South"
      ]
}

We could disable the test in ARM-TTK, but is there a better way?

A suggestion one person made was if there are allowed values then the defaultValue must be one of them, even if it means it hardcoded as the intention is to limit the locations.

**Comment by bmoore-msft** [comment]
Got it - disabling the test is probably the right answer short term, if you don't care about the defaultValues (or use skipByFile)...

The spirit of the test is that it's not a great practice to hardcode a location, even as a defaultValue.  When you have allowedValues there's not much chance of having an error from the user so best to just remove it.

There is another question of whether bicep should flag the defaultValue of [resourceGroup().location] (because deployment will fail) but TTK generally does not catch things that will be caught during validate (because we don't have the resources to duplicate the validate api).

I'm going to close as "by design" lmk if you see a flaw in the logic here...
