### ISSUE TITLE
apiVersion should be recent - Automation Account

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#463]
This snippet shoudl trigger the rule apiVersion Should be recent test
    {
      "type": "Microsoft.Automation/automationAccounts",
      "apiVersion": "2020-01-12",
      "name": "[parameters('automationAccountName')]",
      "location": "[parameters('Location')]",
      "properties": {
        "sku": {
          "name": "Free"
        }
      }
}

However if the apiVersion is not one documented, in Azure,  then the test seems to pass, in this case the apiVersion is not listed by Azure for the resource type.

**Comment by bmoore-msft** [comment]
@drewkg - just to make sure I understand... are you saying the test should flag 2020-01-12 for automations accounts because it is *not* a valid apiVersion?  (I don't see it listed in the manifest).

If so, the reason we don't do that is that the manifest often lags the service and we don't want to flag an apiVersion that will work.  When these gaps exist it can take a long time to close them (unfortunately).  It's more common with newer or "the latest" apiVersion.  If the apiVersion is not valid, it will be caught very early in the deployment cycle.

Or is your scenario different?

**Comment by drewkg** [comment]
@bmoore-msft Thanks for the explanation, I guess this is partially one of the reasons VSCode is often out of date on the possible API versions.

In this case I was resolving the use of a preview API, which was required for the newer functionality, and I inadvertently used an API version that is not supported.  ARM TTK passed the version, VS Code flagged up the fact it is not in the schema(but I ignore this as it is often out of date).

In this case to actually deploy the template, takes around 3 hours, so we do not run the deployment very often.  But I can understand the reasoning please make it as closed, so we can see the outcome if anyone else has the same issue.,

**Comment by bmoore-msft** [comment]
One thing we *could* do here is throw a warning - like we do with the outdated schema... thoughts?

**Comment by drewkg** [comment]
I am not sure, there are two use cases we have
1. running locally, in which case a warning would be very useful
2. In a pipeline, but in this case if the warning broke the build we would have to disable the test too often as quiet often the latest API is not in the schema yet.

**Comment by bmoore-msft** [comment]
re: #2 - yes, you'd have to decide if that particular case should fail the build or "succeed with errors"...  I would assert that in a pipeline, you ignore the warning and if it is indeed incorrect will be caught in deployment.  As you noted, sometimes that can take a while, but by the time the code is checked in (and running in the pipeline) you should know whether the apiVersion is valid or not...  So IOW, ignore the warning in the pipeline because the apiVersion is correct (because it was validated by dev, prior to check-in.

**Comment by drewkg** [comment]
Can you suppress a test just for one resource type? this would be ideal but probably impractical for the edge case we are discussing here.

As we adopt ARM-TTK in pipelines, we have a workflow to regularly review any supressed tests with the ideal to remove all suppression's where they were due to transient issues rather then something we had purposely done.

So probably a warning if the API is not valid at all, with the understanding that it may need to be suppressed in the situation where a most recent API version is not yet in the cache.

**Comment by bmoore-msft** [comment]
Not today - one option would be to provide your own version of the cache that is used for checking apiVersions... and simply add the version you know is good.  Though seems that seems like more work (and is reactive) than figuring out how to deal with the warning...

**Comment by bmoore-msft** [comment]
Ok, in #470 - I added a warning for an "unknown" apiVersion - going to close this against that, lmk if that doesn't seem right...
