### ISSUE TITLE
Reasons we need to use "empty" or null values.

### ISSUE THREAD

**Issue by marrobi** [Azure/arm-ttk#50]
On occasion we need to use empty values, as per the following example: 
```
"empty": [
        ],
"subnets": "[union(variables('defaultSubnets'),if(parameters('deployVnetGateway'), variables('gatewaySubnet'),variables('empty')),if(parameters('deployBastion'), variables('bastionSubnet'),variables('empty')))]",
```

This failed arm-ttk validation. I have managed to workaround as follows, but the logic is a lot harder to follow!

```
"subnetLogicGateway": "[if(parameters('deployVnetGateway'),union(variables('defaultSubnets'),variables('gatewaySubnet')),variables('defaultSubnets'))]",
        "subnetLogicBastionGateway": "[if(parameters('deployBastion'),union(variables('subnetLogicGateway'),variables('bastionSubnet')),variables('subnetLogicGateway'))]",
        "subnets": "[variables('subnetLogicBastionGateway')]",
 ```

**Comment by bmoore-msft** [comment]
I think subnets[] may be something we need to except, but in this case I think using json('null') is correct?

**Comment by marrobi** [comment]
Not sure subnets[] would work. As it can be different resources that take an array. Firewall rules for example.

Are you saying json('null') should work? Sure I tried it, but can try again might have been the union function that didn't like it. 

Can give it another go tomorrow.

**Comment by bmoore-msft** [comment]
oic - it's flagging the empty variable... 

Instead of an empty variable use: json('[]') in your "else" side of the if() statement

**Comment by marrobi** [comment]
So `json('[]')`:

```   
"subnets": "[union(variables('defaultSubnets'),if(parameters('deployVnetGateway'), variables('vnetGatewaySubnet'),json('[]') ),if(parameters('deployBastion'), variables('bastionSubnet'),json('[]') ))]",
```

Fails ARM-TTK due to empty value.

and `json('null')`:
```
"subnets": "[union(variables('defaultSubnets'),if(parameters('deployVnetGateway'), variables('vnetGatewaySubnet'),json('null') ),if(parameters('deployBastion'), variables('bastionSubnet'),json('null') ))]",
```       
Gives:

```
Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The template variable 'subnets' is not valid: Template language function 'union' expects parameters of
     | the same type, but found multiple types..
```

**Comment by amergey** [comment]
Very similar needs for us 
We need to "transform" a variable list of parameters  into an array so we use this kind of thing (which is simplified to illustrate here) : 
[union(array('val'),if(empty(parameters('param')),json('[]'),array(parameters('anotherVal'))))]

this is failing because json('[]') is considered as an empty property for "Template Should Not Contain Blanks" 

There is probably alternative way to do achieve that without json('[]') but harder to follow

**Comment by bmoore-msft** [comment]
Ack... json('[]') was working for me (i.e. tests didn't flag it) due to user error (I used it in an output which is already excepted).  Anyway....

So I could think of a few options here:

1) allow certain variable names to be empty
Generally I think if you use an empty Var you know why you're doing it and it's intentional...  the flip side is that you would miss come cases where you don't want it directly assigned to a property.  So I could say any variable that is named something like "empty*" would be ignored by the test.  That requires you to know about the "magic" naming convention to bypass the test

2) except the json() function specifically
Indirectly we do this for json('null') today, we could do it (easily) for any time the empty json is not preceded by colon.  This would required the template author to use the json() function anytime you want to use empty...  it would also mean the test would not flag incorrect use of empty, but that's extremely rare in practice.

I think I like #2 - thoughts?

**Comment by bmoore-msft** [comment]
or both?

**Comment by amergey** [comment]
I am not the initial reporter of the issue, but I also like #2 :)

**Comment by marrobi** [comment]
2 works for me. Unless there are instances other than empty arrays that can be dealt with using the same logic, such as '{}'.

**Comment by bmoore-msft** [comment]
yes, I think the logic would work the same for empty objects, strings, nulls...  So the cases we would catch are where you literally specify an empty property (regardless of type)... which TBH is the common case and the common mistake.  If you've authored it as an expression, you're intentionally doing so.

**Comment by bmoore-msft** [comment]
added an approach in #62
