### ISSUE TITLE
Should there be a rule to make sure fileUris using secure parameters for custom scripts go in protectedSettings?

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/arm-ttk#529]
See https://github.com/Azure/custom-script-extension-linux/issues/73

**Comment by StephenWeatherford** [comment]
See also https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#property-value-details

**Comment by bmoore-msft** [comment]
The reason we don't do uri's is that they are often needed for debugging... and once put inside of protected settings very difficult to get out.  So if the resource is failing because it can't find the file, then you need to know what file it was actually looking for (as uris are often constructed at deploy time).

We could add the rule but then you'd want to ignore it until it was well tested (i.e. on more than just the developer's machine/subscription)...  possible, but not sure we have any other rules like that?

**Comment by StartAutomating** [comment]
Not considering new validation at this time.
