### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by alexey-nikolov-basemark-com** [Azure/arm-ttk#600]
Hi

Please add the actual version string somewhere in obvious places: the release artifact file name, in the top directory name, in the utility outputs etc. It's terribly difficult to follow

**Comment by bmoore-msft** [comment]
Not sure I follow - can you expand a bit?

**Comment by alexey-nikolov-basemark-com** [comment]
Sure. Here's a customer workflow with an `atm-ttk` release:
* Download release version 2022.03.04 from https://github.com/Azure/arm-ttk/releases/tag/2022.03.04. Result is an unversioned file `arm-ttk.zip`
* Extract the release file. Result is a file tree with unvesioned top directory `arm-ttk`.
* Run the `Test-AzTemplate`. Result is console output without mentioning the version. There's also no command line parameter to print the version string (i.e. `--version`)

Some time passed, one wouldn't be able to tell which release version is in use. Suggestion is to put the version string everywhere mentioned above.

**Comment by alexey-nikolov-basemark-com** [comment]
Would be nice if you follow this https://www.gnu.org/prep/standards/html_node/Releases.html

**Comment by bmoore-msft** [comment]
Got it - so basically a way to tell what version of the TTK is in use by running a command?

**Comment by alexey-nikolov-basemark-com** [comment]
At the very least, yes, thank you

**Comment by beavel** [comment]
In addition to or as an alternative, could the module itself get version updates per release? That would also help solve some issues around knowing what version of the module is installed and do so in a way that is native to PowerShell. It would also allow side-by-side installation of the modules so you can upgrade and import based on version instead of having to wipe the directory it is installed in and copy in new.

I found this issue because I came here looking to get latest again and saw the module version is still the same as the original release. I was hoping to be able to install the latest next to what I had used previously.

**Comment by bmoore-msft** [comment]
Ok, we're going to start with bumping the module version... so when we have a new release in the repo, the version in the psd1 will also be updated.

That will enable a ```Get-Module arm-ttk``` experience like pretty much every other powershell module.

LMK if that's still missing something...

**Comment by beavel** [comment]
That works for me! 

I still think adding the version number to the download would be helpful as the OP had requested. I'm thinking the release number in the download file name and folder with the module version. That way release version, assuming you stick with the current convention, would be tied to the module version. It would also allow you to extract the folder as is instead of having to make the matching version number folder in module folder.

**Comment by bmoore-msft** [comment]
> I still think adding the version number to the download would be helpful as the OP had requested. I'm thinking the release number in the download file name and folder with the module version. That way release version, assuming you stick with the current convention, would be tied to the module version. It would also allow you to extract the folder as is instead of having to make the matching version number folder in module folder.

The challenge with having a different filename for every release means you never know the filename for ```https://github.com/Azure/arm-ttk/releases/latest/...```

If you want to be strongly versioned in your downloads, you can do that via the path, but if you wanted to always grab the latest, you couldn't if we keep changing the filename...

**Comment by beavel** [comment]
That's a fair point. What's the difference between the version published on github.com and what is published here: https://aka.ms/arm-ttk-latest? That is what is published on [the docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit), so wondering if that could server as the URL to grab latest.

**Comment by bmoore-msft** [comment]
Before we had GH releases, the aka.ms link had "the latest" as we really only published one version of the TTK, when we started releases, the aka.ms link became the "dogfood" release, we use it in the QuickStart repo to test it out for a bit before we would release to GH.  Not sure if we still need that distinction, esp since it's not very obvious.

**Comment by bmoore-msft** [comment]
So we now have the PSD1 updates (so the module version increments) along with GH releases... I think we'll close this one now, shout if you think there's anything we're missing.
