### ISSUE TITLE
Microsoft.Authorization/roleDefinitions API Version reports as too old despite being the most recent from swagger

### ISSUE THREAD

**Issue by ReneRebsdorf** [Azure/arm-ttk#642]
Hi

When using this resource: Microsoft.Authorization/roleDefinitions@2018-01-01-preview

ARM-TTK gives error on API being too old.
The AllAzureResources.cache.json has an apiVersion of 2018-07-01

The most recent version available [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.authorization/roledefinitions?tabs=bicep) is 2018-01-01-preview

The bicep linter reports 2018-07-01 does not have linters available.

So it seems we can have to either trade type validation + documentation vs. a valid arm-ttk test.

Can we get validation + docs updated (preferably), or remove 2018-07-01 as a valid version from the cache, given it seems to be "undocumented"?

**Comment by bmoore-msft** [comment]
TTK is pulling from the manifest in production - 2018-07-01 is the latest there... So that's in prod.

ack on getting the docs and tooling (i.e. swagger) to match...  Can you file this issue in the bicep repo (i.e. missing apiVersion)? 
 They tend to have a good/better track record of getting platform changes in...

**Comment by ReneRebsdorf** [comment]
@bmoore-msft I see 'wsmelton' beat me to it [with this issue](https://github.com/Azure/bicep/issues/6610)

Based on your recommendation to post in biceps issue tracker, I am closing this issue with the above reference.
